### ISSUE TITLE
how to obtain stable and accurate camera poses?

### ISSUE THREAD

**Issue by Techhooli** [zju3dv/NeuralRecon#36]
From Demo, the arkit from apple can provide the stable and accurate camera poses. I have try to use orb-slam2 and VINS to calculate the poses of some images which are captured from phones. Of course, Your program can output a ply model. But its shape is not good. So I think maybe the image poses are not accurate. Do you know why the iphone can provide the accurate camera poses? I think it also used the VIO algorithm. Do you think SLAM can be used to provided the poses of images?

**Comment by JiamingSuen** [comment]
> Do you know why the iphone can provide the accurate camera poses?

Because ARKit is well-optimized in both hardware and software by the brilliant engineers at Apple 😉.

> Do you think SLAM can be used to provided the poses of images?

I'm not an expert in SLAM, with that being said, I think it would require some significant effort to tune the hardware and software in a custom open-sourced VI-SLAM system to match the accuracy of ARKit. Thus I recommend you to stick with ARKit to run NeuralRecon.
